# language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t hodgsondh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hodgsondh/docker-react npm run test -- --coverage