# language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t hodgsondh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hodgsondh/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-831906403070"
  bucket_path: "docker-react" # same as app name
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  # http://dockerreact-env.eba-fnikhv6b.us-east-2.elasticbeanstalk.com/